### ISSUE TITLE
How to deal with with repeat segments?

### ISSUE THREAD

**Issue by wiegell** [shogg/edifact#11]
Hello there @shogg, thanks for making this package.
I have tried it for a project at work, but we have repeat segment statements, and i don't see a way to extract them with this package?

There is actually also one in the ORDERS spec:
<img width="822" alt="image" src="https://github.com/shogg/edifact/assets/29224981/6e97f4db-e1ff-4bb1-b153-0a615b37658e">
I don't see a clear syntax as to how to extract both lines, i tried:
<img width="516" alt="image" src="https://github.com/shogg/edifact/assets/29224981/05e73a34-3c66-428a-a37a-e50695c0ffd3">
But that gives:
<img width="430" alt="image" src="https://github.com/shogg/edifact/assets/29224981/d9a50957-c32c-4ed3-aa4a-8c0afa5e4329">

And in our project i also tried making a "fake" segment group (not in my standardised spec), with only the one FTX tag, to try and parse the repeat segments to an array (which is what i really want), but couldn't get it to work either.
To complicate it further, our spec actually has a single mandatory `FTX+ACM` followed by 20 conditional `FTX+SPC`, so the base tag is the same! (i would be glad with just one single array including both `FTX+ACM` and `FTX+SPC`)
Here is an example:
```
FTX+ACM+P00++Væsentlige fejlstillinger;højre fod'
FTX+SPC+P00++Mobil pes planus transversus?:Ja'
FTX+SPC+P00++Hallux valgus?:Ja'
```
We consume a variant of this spec:
https://service.unece.org/trade/untdid/d09a/trmd/medrpt_c.htm

Hope to hear from you, kind regards

**Comment by shogg** [comment]
I have a simple patch for `Comments []string`. `Comment1, Comment2` will still not work. Tomorrow I'll test corner cases before pushing.

**Comment by wiegell** [comment]
Wow that would be amazing! thank you! `Comments []string` is the ideal case

**Comment by shogg** [comment]
I pushed the patch.

There is a new test in `unmarshal_rffs_test.go` to show what to expect when unmarshalling into a slice.

**Comment by wiegell** [comment]
it works perfectly, thanks alot!
