### ISSUE TITLE
issue with decoding 201 dates

### ISSUE THREAD

**Issue by deftstar** [shogg/edifact#13]
this seems to be wrong 
`case dtmFormat201, dtmFormat203:
		format = "200601021504"`

//decode.go 124

201 on edi docs it is represented as "0601021504"
201   YYMMDDHHMM

as such i am unable to decode dates

**Comment by shogg** [comment]
I saw your commits, MalidivesPorts. You're so impatient. But you're free to do what you want. Issue closed, in either way.

**Comment by deftstar** [comment]
thank you for the fix and yeah i was in a hurry but assumed it would be helpful to point out the issue.
